// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

import (
	"github.com/hironow/team-lgtm/backend/lgtm"
	"github.com/hironow/team-lgtm/backend/todo"
)

type LGTMConnection struct {
	Cursor  string       `json:"cursor"`
	HasMore bool         `json:"hasMore"`
	Lgtms   []*lgtm.LGTM `json:"lgtms"`
}

type NewLgtm struct {
	Description string `json:"description"`
}

type NewSignIn struct {
	Name *string `json:"name"`
}

type NewSignUp struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text string `json:"text"`
}

type TodoConnection struct {
	Cursor  string       `json:"cursor"`
	HasMore bool         `json:"hasMore"`
	Todos   []*todo.Todo `json:"todos"`
}
