// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type NewSignIn struct {
	Name *string `json:"name"`
}

type NewSignUp struct {
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}
